### PR TITLE
add wildcard check for cname also

### PR DESCRIPTION
**Pull request by h888t**

### CODE REVIEW

**Comment by bp0lr** [comment]
Hello!, thank you for this PR.

can you give me some DNS to check what it does?

thank you!

**Comment by h888t** [comment]
Sure! <random>.snowflakecomputing.com is a good example.

The previous version would correctly identify A record wildcards, but sadly not CNAME wildcards - but was using existence of a CNAME record to indicate a real discovery, thus leading to false positives 

Great tool, thanks for building this!

**Comment by h888t** [comment]
@bp0lr any update on merging this? :-)

**Comment by bp0lr** [comment]
hi!
looks good to me!

thank you

**Comment by h888t** [comment]
🚀🚀🚀 thank you

**Comment by bp0lr** [comment]
Hey! Doing a little overdue housekeeping 🙂 This was already fixed in PR #16. Thanks for the contribution!

**Pull request merged**
